project:
  type: website
  output-dir: docs_local

#----------------------------------
# project:
#   type: website

# website:
#   title: "VincentChong123.github.io"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true



